import { prisma } from './client.js';
import { TENANT_SCOPED_MODEL_NAMES } from './tenant-models.generated.js';
import type { WorkspaceId } from '@shared/brand.js';

/**
 * Tenant enforcement.
 *
 * The realistic threat is not a malicious developer — it is one forgotten
 * `where` clause, eighteen months from now, in a hurry, by someone who has not
 * read the docs. So the filter is injected rather than remembered. See ADR-0005.
 */

/**
 * Derived from the schema, not hand-maintained: any model carrying a
 * `workspaceId` field is covered automatically, which means a new table is
 * protected the moment it is created rather than when someone remembers to
 * register it here.
 *
 * Regenerated by `pnpm db:generate` — see scripts/generate-tenant-models.ts.
 */
export const TENANT_SCOPED_MODELS: ReadonlySet<string> = new Set(TENANT_SCOPED_MODEL_NAMES);

const CREATE_OPERATIONS = new Set(['create', 'createMany', 'createManyAndReturn']);

const WHERE_OPERATIONS = new Set([
  'findFirst',
  'findFirstOrThrow',
  'findMany',
  'count',
  'aggregate',
  'groupBy',
  'update',
  'updateMany',
  'delete',
  'deleteMany',
]);

/**
 * `findUnique` accepts only unique fields in `where`, so injecting
 * `workspaceId` there is rejected by Prisma. Rewriting to the non-unique
 * equivalent keeps the guarantee without asking callers to remember which
 * finder they used.
 */
const UNIQUE_REWRITES: Readonly<Record<string, string>> = {
  findUnique: 'findFirst',
  findUniqueOrThrow: 'findFirstOrThrow',
};

type AnyArgs = Record<string, unknown>;
type Delegate = Record<string, (args: unknown) => unknown>;

const merge = (value: unknown, workspaceId: string): AnyArgs => ({
  ...(typeof value === 'object' && value !== null ? (value as AnyArgs) : {}),
  workspaceId,
});

const lowerFirst = (s: string): string => s.charAt(0).toLowerCase() + s.slice(1);

export type TenantClient = ReturnType<typeof tenantClient>;

export function tenantClient(workspaceId: WorkspaceId | string) {
  return prisma.$extends({
    name: 'tenant-scope',
    query: {
      $allModels: {
        // Must be async: Prisma types the extension callback as returning a
        // Promise, and the rewrite branch below calls another delegate.
        async $allOperations({ model, operation, args, query }) {
          if (!TENANT_SCOPED_MODELS.has(model)) return query(args);

          const a: AnyArgs = args;

          if (CREATE_OPERATIONS.has(operation)) {
            a.data = Array.isArray(a.data)
              ? a.data.map((row) => merge(row, workspaceId))
              : merge(a.data, workspaceId);
            return query(args);
          }

          if (operation === 'upsert') {
            a.where = merge(a.where, workspaceId);
            a.create = merge(a.create, workspaceId);
            return query(args);
          }

          const rewritten = UNIQUE_REWRITES[operation];
          if (rewritten) {
            a.where = merge(a.where, workspaceId);
            const delegate = (prisma as unknown as Record<string, Delegate>)[lowerFirst(model)];
            const fn = delegate?.[rewritten];
            if (fn) return fn(args);
            return query(args);
          }

          if (WHERE_OPERATIONS.has(operation)) {
            a.where = merge(a.where, workspaceId);
          }

          return query(args);
        },
      },
    },
  });
}
