// GENERATED by scripts/generate-tenant-models.ts — do not edit.
// Run `pnpm db:generate` after changing prisma/schema.prisma.
//
// Models carrying a scalar `workspaceId` are tenant-scoped: the tenant client
// injects the workspace filter on every read and write. See ADR-0005.

/** Models the tenant client scopes automatically. */
export const TENANT_SCOPED_MODEL_NAMES = [
  'AuditLog',
  'Commit',
  'Developer',
  'DeveloperDailyRollup',
  'DeveloperIdentity',
  'Insight',
  'Integration',
  'Issue',
  'MetricSnapshot',
  'Notification',
  'PullRequest',
  'PullRequestReview',
  'RawEvent',
  'Report',
  'Repository',
  'RepositoryContributor',
  'RepositoryDailyRollup',
  'ScoreSnapshot',
  'SyncCursor',
  'SyncRun',
  'Team',
  'TeamDailyRollup',
  'TeamMember',
  'WorkspaceMember',
] as const;

/**
 * Models with no `workspaceId`. Each one is intentionally global — adding a
 * model here means asserting that it holds no tenant data.
 */
export const GLOBAL_MODEL_NAMES = [
  'Session',
  'User',
  'UserOAuthAccount',
  'Workspace',
] as const;

export type TenantScopedModel = (typeof TENANT_SCOPED_MODEL_NAMES)[number];
export type GlobalModel = (typeof GLOBAL_MODEL_NAMES)[number];
