/**
 * Derives the list of tenant-scoped Prisma models from the schema.
 *
 * ADR-0005 requires this list to be *derived*, never hand-maintained: a new
 * table must be protected the moment it is created, not when someone remembers
 * to register it. Prisma 7 no longer exposes `Prisma.dmmf` from the generated
 * namespace, so rather than depend on an internal runtime field we generate the
 * constant from the schema as part of `db:generate`.
 *
 * Run: pnpm db:generate
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SCHEMA = resolve('prisma/schema.prisma');
const OUT = resolve('src/db/tenant-models.generated.ts');

const source = readFileSync(SCHEMA, 'utf8');

// Model blocks: `model Name {  ...  }` at the top level.
const modelBlock = /^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm;

const scoped: string[] = [];
const unscoped: string[] = [];

for (const match of source.matchAll(modelBlock)) {
  const name = match[1];
  const body = match[2];
  if (!name || !body) continue;

  // A scalar `workspaceId` field, not the `workspace` relation.
  const hasWorkspaceId = /^\s*workspaceId\s+String/m.test(body);
  (hasWorkspaceId ? scoped : unscoped).push(name);
}

scoped.sort();
unscoped.sort();

const banner = `// GENERATED by scripts/generate-tenant-models.ts — do not edit.
// Run \`pnpm db:generate\` after changing prisma/schema.prisma.
//
// Models carrying a scalar \`workspaceId\` are tenant-scoped: the tenant client
// injects the workspace filter on every read and write. See ADR-0005.
`;

const body = `${banner}
/** Models the tenant client scopes automatically. */
export const TENANT_SCOPED_MODEL_NAMES = [
${scoped.map((m) => `  '${m}',`).join('\n')}
] as const;

/**
 * Models with no \`workspaceId\`. Each one is intentionally global — adding a
 * model here means asserting that it holds no tenant data.
 */
export const GLOBAL_MODEL_NAMES = [
${unscoped.map((m) => `  '${m}',`).join('\n')}
] as const;

export type TenantScopedModel = (typeof TENANT_SCOPED_MODEL_NAMES)[number];
export type GlobalModel = (typeof GLOBAL_MODEL_NAMES)[number];
`;

writeFileSync(OUT, body, 'utf8');

console.warn(
  `tenant models: ${scoped.length} scoped, ${unscoped.length} global -> src/db/tenant-models.generated.ts`,
);
